language: go

services:
  - docker

before_install:
  - docker image build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .

script:
  - docker container run -p 8888:8888 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
