language: go

services:
  - docker

script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t multi-nginx ./nginx
    - docker images
    - docker tag multi-nginx $DOCKER_USERNAME/multi-nginx
    - docker push $DOCKER_USERNAME/multi-nginx