language: go

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker image build -t $DOCKER_USERNAME/multi-nginx ./nginx
      - docker image build -t $DOCKER_USERNAME/multi-client ./client
      - docker image build -t $DOCKER_USERNAME/multi-server ./server
      - docker images
      - docker push $DOCKER_USERNAME/multi-nginx
      - docker push $DOCKER_USERNAME/multi-client
      - docker push $DOCKER_USERNAME/multi-server
