language: go

services:
  - docker

before_install:
  - docker image build -t satioO:multi-client ./client
  - docker image build -t satioO:multi-server ./server
  - docker image build -t satioO:multi-nginx ./nginx

after_success:
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to docker hub
  - docker push satioO:multi-client
  - docker push satioO:multi-server
  - docker push satioO:multi-nginx