language: go

services:
  - docker

before_install:
  - docker image build --no-cache -t beanstalk:${TRAVIS_COMMIT} .
  - docker container run -d -p 127.0.0.1:8888:8888 beanstalk:${TRAVIS_COMMIT}

script:
  - curl 127.0.0.1:8888
