language: go

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker image build -t $DOCKER_USERNAME/multi-nginx ./nginx
      - docker image build -t $DOCKER_USERNAME/multi-client ./client
      - docker image build -t $DOCKER_USERNAME/multi-server ./server
      - docker images
      - docker push $DOCKER_USERNAME/multi-nginx
      - docker push $DOCKER_USERNAME/multi-client
      - docker push $DOCKER_USERNAME/multi-server
    - stage: before deploy
      before_deploy: 
        - echo $AWS_ACCESS_KEY
        - echo $AWS_SECRET_KEY
    - stage: deploy
      deploy:
        provider: elasticbeanstalk
        access_key_id:
          secure: $AWS_ACCESS_KEY
        secret_access_key:
          secure: $AWS_SECRET_KEY
        region: "ap-south-1"
        app: "docker-deploy"
        env: "DockerDeploy-env"
        bucket_name: "elasticbeanstalk-ap-south-1-327637452640"
        bucket_path: "docker-deploy"
        on:
          branch: main

        

