version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8888:80"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=users # database name you want to make
      - MONGO_INITDB_ROOT_USERNAME=root # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=root # set your contatner root password
    volumes:
      - ./data/db:/data/db
  api:
    depends_on:
      - mongo
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - FOO=Root
      - BAR=Groot
