apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-client-pod
        tier: frontend
    spec:
      containers:
      - name: client
        image: vaibhavsatam/multi-client
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
  selector:
    matchLabels:
      app: multi-client-pod
      tier: frontend
