apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-server-pod
        tier: server
    spec:
      containers:
      - name: server
        image: vaibhavsatam/multi-server
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_HOST
            value: mongo-cluster-ip-service
  selector:
    matchLabels:
      app: multi-server-pod
      tier: server
