apiVersion: v1
kind: Service
metadata:
  name: multi-client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: multi-client-pod
    tier: frontend
  ports:
  - port: 3000
    targetPort: 3000
