apiVersion: v1
kind: Service
metadata:
  name: multi-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: multi-server-pod
    tier: server
  ports:
  - port: 5000
    targetPort: 5000
